insert into adress (fk_customer_id, street, house_number, zip_code, city) values (1, 'Merry', '817', 'none', 'Álimos');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (2, 'Karstens', '81727', '827 24', 'Ljusdal');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (3, 'Granby', '44149', '963-8823', 'Furukawa');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (4, 'Knutson', '42852', '544 75', 'Zadní Mostek');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (5, 'Transport', '3910', '9209', 'Payabon');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (6, 'Sachs', '05', '96640-000', 'Rio Pardo');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (7, 'Redwing', '229', 'none', 'San Pablo');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (8, 'Packers', '7', 'none', 'Sangiyn Dalay');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (9, 'Stang', '1', 'none', 'Laç');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (10, 'Merry', '991', 'none', 'Xarrë');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (11, 'Graceland', '21', '86165-000', 'Florestópolis');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (12, 'Melvin', '892', 'none', 'Beicheng');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (13, 'Upham', '4', 'none', 'Lichengdao');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (14, 'Scott', '3925', 'none', 'Tagiura');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (15, 'Cherokee', '989', '613645', 'Krasnyy Yar');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (16, 'Myrtle', '324', 'none', 'Laxiong');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (17, 'Michigan', '373', 'none', 'Cidadap');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (18, 'Onsgard', '264', '4760-421', 'Cavalões');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (19, 'Di Loreto', '193', 'none', 'Yashan');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (20, 'Dennis', '29', 'P81', 'Cloyne');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (21, 'Vera', '03295', '11403', 'Hostos');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (22, 'Kropf', '736', 'none', 'Dongsheng');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (23, 'Center', '6200', 'none', 'Ekou');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (24, 'Ridgeview', '49001', '929-0417', 'Sakado');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (25, 'Ludington', '08775', '164051', 'Voloshka');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (26, '6th', '42538', 'none', 'Xiayang');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (27, 'Hanover', '2829', '24-130', 'Końskowola');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (28, 'Briar Crest', '115', '40210', 'Nong Ruea');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (29, 'Buhler', '254', 'none', 'Shuanghekou');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (30, 'Victoria', '41344', 'none', 'Leshan');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (31, 'Parkside', '962', 'none', 'Dagang');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (32, 'Center', '104', '87490-000', 'Nova Olímpia');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (33, 'Brentwood', '46', 'none', 'Okhtyrka');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (34, 'Fisk', '19', '969-1783', 'Tottori');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (35, 'Golden Leaf', '31040', 'none', 'Druzhny');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (36, 'Pond', '0', 'none', 'Gongji');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (37, 'Bashford', '85', '69446 CEDEX 03', 'Lyon');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (38, 'Crescent Oaks', '91', '4274', 'Slovenski Javornik');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (39, 'Gateway', '64857', '382 21', 'Kájov');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (40, 'Lillian', '629', 'none', 'Jiulian');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (41, 'Di Loreto', '349', 'none', 'Olmos');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (42, 'Sundown', '2', '5400-339', 'Valongo');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (43, 'Thackeray', '366', 'none', 'Huangdao');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (44, 'Nelson', '99', 'none', 'Maevatanana');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (45, 'Lillian', '639', 'none', 'Ccatca');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (46, 'Almo', '295', '02104 CEDEX', 'Saint-Quentin');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (47, 'Straubel', '8', 'none', 'Wang’er');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (48, 'Green Ridge', '96', '779-3601', 'Haibara');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (49, 'Ridgeview', '2', 'none', 'Yalukou');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (50, 'Myrtle', '97838', '1114', 'Lucapon');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (51, 'Spenser', '07', 'none', 'Pingyang');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (52, 'Arizona', '108', 'none', 'Cigalontang');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (53, 'Holy Cross', '33', 'none', 'Kaliwates');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (54, 'Doe Crossing', '5685', 'none', 'Changliu');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (55, 'La Follette', '00', 'none', 'Viļaka');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (56, 'Valley Edge', '00609', '2430-149', 'Guarda Nova');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (57, 'Beilfuss', '60993', '40054', 'Las Palmas');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (58, 'Golden Leaf', '64292', 'none', 'Kýthnos');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (59, 'Talisman', '7635', 'none', 'Hengtanggang');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (60, 'Lunder', '7248', 'none', 'Rizómilos');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (61, 'Bultman', '41701', 'none', 'Yidu');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (62, 'Evergreen', '7631', '798 43', 'Ptení');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (63, 'Waywood', '57', '478008', 'Ciénaga');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (64, 'Waywood', '44314', 'none', 'Ranisoba');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (65, 'Sullivan', '53686', '1354', 'Verd');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (66, 'Luster', '20651', '959-2073', 'Kamifukuoka');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (67, 'Orin', '4563', 'none', 'Suining');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (68, 'Brown', '9', 'none', 'Ciyun');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (69, 'Warner', '400', '2433', 'San Fabian');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (70, 'Gale', '3', '6583', 'Knysna');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (71, 'Moose', '29870', 'none', 'Yufrus');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (72, 'Sheridan', '14368', 'none', 'Quchi');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (73, 'Upham', '7302', 'none', 'Xiaolong');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (74, 'Lien', '8', 'none', 'Xiejiaya');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (75, 'Porter', '740', 'J3H', 'Beloeil');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (76, 'Fairview', '95800', 'none', 'Srunikrajan');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (77, 'Walton', '8', '5216', 'Dinājpur');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (78, 'Transport', '4144', '30330', 'Chachoengsao');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (79, 'Stephen', '48', 'D6W', 'Dundrum');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (80, 'Bunting', '60429', '88998', 'Kota Kinabalu');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (81, 'Doe Crossing', '80474', 'none', 'Gensi');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (82, 'Anderson', '36', 'none', 'Kuwumkumambal');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (83, 'Autumn Leaf', '9133', '62800-000', 'Aracati');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (84, 'Crowley', '0456', 'none', 'Babakan');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (85, 'Ridge Oak', '92115', 'none', 'Hekou');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (86, 'Roxbury', '9175', '4700-005', 'Braga');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (87, 'Westend', '11', 'none', 'Aībak');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (88, 'Village', '471', '98670-000', 'Humaitá');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (89, 'Lyons', '42', 'none', 'Boju');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (90, 'Golden Leaf', '56', '135067', 'Cantagallo');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (91, '7th', '26', '862 95', 'Njurunda');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (92, 'Montana', '41066', '431355', 'Kovylkino');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (93, 'Knutson', '27452', '76130', 'Sann');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (94, 'Northwestern', '0901', 'none', 'Yinchuan');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (95, 'Calypso', '16384', '142720', 'Shcherbinka');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (96, 'Calypso', '376', '601270', 'Bogolyubovo');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (97, 'Muir', '1', 'none', 'Dhankutā');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (98, 'Mitchell', '34', 'none', 'Buka');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (99, 'Steensland', '651', '9210', 'Baroy');
insert into adress (fk_customer_id, street, house_number, zip_code, city) values (100, 'Welch', '391', 'none', 'Umm as Sāhik');
