insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (22, 17, 'Titanium Dioxide', 29);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (94, 70, 'PRAVASTATIN SODIUM', 25);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (46, 54, 'mineral/vitamin supplement', 19);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (42, 42, 'Fexofenadine HCl', 14);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (42, 49, 'Amlodipine Besylate and Benazepril Hydrochloride', 22);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (66, 89, 'Hydrocodone Bitartrate and Ibuprofen', 29);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (36, 13, 'TITANIUM DIOXIDE, OXYBENZONE, and OCTINOXATE', 3);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (83, 30, 'ropinirole hydrochloride', 22);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (99, 11, 'Losartan Potassium', 15);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (54, 69, 'iopromide', 27);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (34, 77, 'TITANIUM DIOXIDE, ZINC OXIDE, OCTINOXATE, AMILOXATE, ARBUTIN, ADENOSINE', 28);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (31, 10, 'OCTINOXATE and TITANIUM DIOXIDE', 18);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (66, 76, 'Nabumetone', 23);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (85, 30, 'Pyrogenium, Aconitum nap., Arg. nit., Arsenicum alb., Baptisia, Bryonia, Carbo veg., Chamomilla, Cinchona, Collinsonia, Colocynthis, Elaterium, Gelsemium, Ipecac., Iris versicolor, Lycopodium, Podoph. pelt., Raphanus, Tabacum, Vaccinium, Zingiber, Aesculus hipp., Juglans regia', 9);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (26, 89, 'Berberis vulgaris 3X, Lycopodium clavatum 5X, Nitricum acidum 6X, Sarsaparilla 3X', 14);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (63, 59, 'Oregon Ash', 9);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (59, 14, 'Oxaliplatin', 26);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (4, 34, 'SALICYLIC ACID', 2);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (93, 35, '(WHOLE PLANT)', 13);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (71, 56, 'Potassium Chloride', 25);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (18, 67, 'STANNOUS FLUORIDE', 12);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (26, 46, 'efavirenz, emtricitabine, and tenofovir disoproxil fumarate', 17);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (86, 49, 'Brompheniramine maleate, Dextromethorphan HBr, Phenylephrine HCl', 30);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (8, 86, 'clozapine', 16);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (66, 16, 'ALCOHOL', 18);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (65, 57, 'Ibuprofen', 13);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (18, 95, 'OCTINOXATE', 5);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (83, 65, 'acyclovir', 15);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (64, 14, 'Para Grass Pollen', 3);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (68, 80, 'rivastigmine tartrate', 30);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (44, 40, 'Belladonna, Calcarea carbonica, China officinalis, Glonoinum, Lilium Tigrinum, Platinum metallicum, Pulsatilla, Sanguinaria canadensis, Stannum metallicum, Sulfur', 19);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (32, 34, 'Wheat Bran', 1);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (91, 74, 'HYDROCORTISONE ACETATE', 11);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (62, 58, 'Acetaminophen', 20);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (3, 48, 'Fluorouracil', 23);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (59, 33, 'Menthol', 10);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (93, 44, 'Betamethasone dipropionate', 23);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (21, 7, 'Leucine, Phenylalanine, Lysine hydrochloride, Methionine, Isoleucine, Valine, Histidine, Threonine, Tryptophan, Alanine, Glycine, Arginine, Proline, Tyrosine, Serine', 21);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (95, 69, 'perampanel', 30);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (43, 13, 'Fusarium spp', 16);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (51, 12, 'zinc acetate', 18);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (26, 65, 'Duck Feathers', 19);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (68, 81, 'alprazolam', 29);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (84, 55, 'calcium carbonate', 20);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (80, 82, 'Dicloxacillin Sodium', 12);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (73, 99, 'Flutamide', 22);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (29, 22, 'SODIUM FLUORIDE', 26);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (91, 17, 'mineral oil, petrolatum, phenylephrine HCl', 5);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (56, 36, 'amlodipine besylate', 25);
insert into article (fk_delivery_company_id, fk_producer_company_id, name, price) values (7, 35, 'Guaifenesin', 16);